"""Inline kpi_common into each action so it can be pasted into Turbine.

A Turbine Python action is one code block - it cannot import a sibling file.
This script rewrites each numbered action into a single self-contained file
under ``dist/``, ready to paste:

    python3 bundle_for_turbine.py
    python3 bundle_for_turbine.py --out-dir dist --check

``--check`` re-imports every bundle and asserts it still exposes ``main``,
so a broken bundle fails here rather than in the playbook.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
COMMON = "kpi_common.py"
ACTIONS = [
    "01_normalize_cim_records.py",
    "02_compute_kpi_metrics.py",
    "03_build_trend_series.py",
    "04_build_dashboard_payload.py",
    "05_build_kpi_record_payload.py",
]

FUTURE_RE = re.compile(r"^from __future__ import .*$\n?", re.MULTILINE)
# Matches both the parenthesised multi-line import and a single-line one.
IMPORT_RE = re.compile(r"^from kpi_common import \((?:[^)]*)\)\n|^from kpi_common import .*$\n",
                       re.MULTILINE)


def _split_docstring(source):
    """Return (docstring, body-without-docstring)."""
    tree = ast.parse(source)
    doc = ast.get_docstring(tree)
    if not doc or not tree.body:
        return "", source
    first = tree.body[0]
    lines = source.splitlines(keepends=True)
    body = "".join(lines[first.end_lineno:])
    return doc, body


def _commented(text, prefix="# "):
    return "".join(prefix + line if line.strip() else "#\n"
                   for line in (text or "").splitlines(keepends=True)) + "\n"


def bundle(action_file, common_source):
    with open(os.path.join(HERE, action_file)) as handle:
        action_source = handle.read()

    action_doc, action_body = _split_docstring(action_source)
    _, common_body = _split_docstring(common_source)

    action_body = IMPORT_RE.sub("", action_body)
    action_body = FUTURE_RE.sub("", action_body)
    common_body = FUTURE_RE.sub("", common_body)

    banner = (
        '"""{}\n\nGenerated by bundle_for_turbine.py - do not edit this file.\n'
        'Edit {} or kpi_common.py and re-run the bundler.\n"""\n'
    ).format(action_doc.strip(), action_file)

    return (
        banner
        + "\nfrom __future__ import annotations\n"
        + "\n# " + "-" * 70 + "\n"
        + "# Inlined from kpi_common.py\n"
        + "# " + "-" * 70 + "\n"
        + common_body.rstrip("\n")
        + "\n\n\n# " + "-" * 70 + "\n"
        + "# Action body ({})\n".format(action_file)
        + "# " + "-" * 70 + "\n"
        + action_body.lstrip("\n")
    )


def check(path):
    name = "bundle_" + os.path.splitext(os.path.basename(path))[0].replace(".", "_")
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    if not callable(getattr(module, "main", None)):
        raise AssertionError("{} does not expose a callable main()".format(path))
    return module


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out-dir", default=os.path.join(HERE, "dist"))
    parser.add_argument("--check", action="store_true",
                        help="import each bundle and assert main() exists")
    args = parser.parse_args(argv)

    with open(os.path.join(HERE, COMMON)) as handle:
        common_source = handle.read()

    os.makedirs(args.out_dir, exist_ok=True)
    for action_file in ACTIONS:
        source = bundle(action_file, common_source)
        ast.parse(source)  # fail loudly on a bad rewrite
        out_path = os.path.join(
            args.out_dir, action_file.replace(".py", ".turbine.py"))
        with open(out_path, "w") as handle:
            handle.write(source)
        if args.check:
            check(out_path)
        print("wrote {} ({} lines)".format(out_path, source.count("\n") + 1))
    return 0


if __name__ == "__main__":
    sys.exit(main())
